# Generated by Django 4.2.7 on 2023-11-11 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='date_addes',
            new_name='date_added',
        ),
    ]
