# Generated by Django 4.2.7 on 2023-11-09 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blogpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
